sudo: false
language: scala
sbt_args: -sbt-version 0.13.7
scala:
- 2.11.6
- 2.11.5
- 2.11.4
script:
- sbt clean coverage test coveralls
- sbt coverageReport
- sbt coverageAggregate
- sbt codacyCoverage
after_success:
- sbt doc
- .travis/publish.sh
env:
  global:
    secure: exn9JRP3/A/2WVrlkselkIMj8dSgz9J6sPx3Zg92pSQq0QOURLinWMaNf1eD8gz8g9jZ/HQDxdFMihlkjeh58q2/fyNBonqAzF3gSXKkJwg/uF8gjis+wqdb10y04xxzF24jWE4fy408H0deRFe7QFvMZmnextqrenlWeN4W1zo=
    secure: Ir2L9ZUzhxrAr6vLXWEVOdQelh7YG/CUz8skG4RjwFNdah+8htm75X1NJl8XTkXQ1G/u2gdAJlMxE4Z69xTQmdwsDkXFzVMmLZBTcMlt3qSx+/g0G4Cdat6iqWPsYeQtLzGQGxEoRkCLbtuxe+VxYVX4IxtNA4m00GUK8OuEiM=

before_deploy: sbt assembly
deploy:
  provider: releases
  api_key:
    secure: CFGEZjci7oOf1Orltnn2VyOu4B8feroKOCuUkYps2X1GcAcfB2zc7MWeBidc5BaxsT9zU86tOlIB6lSI5WqM+HNf/9bDR/u2uehbNwpNJQjnTAQSmJjGlKdU98v0+Ahj+O4GW2hm3yAPrghuSI30FjLMV4q8ods/aawcsjrML/k=
  file: target/scala-2.11/deebee.jar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    scala: 2.11.6
